export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
export const SIDEBAR_CHANGE_STATE = 'SIDEBAR_CHANGE_STATE';

export const LOAD_COURSES = 'LOAD_COURSES';
export const LOAD_SPECIFIC_COURSE = 'LOAD_SPECIFIC_COURSE';
export const LOAD_GROUPS = 'LOAD_GROUPS';
export const LOAD_SPECIFIC_GROUPS = 'LOAD_SPECIFIC_GROUPS';
export const DELETE_TASK_GROUP_FROM_ACTIVE_GROUP = 'DELETE_TASK_GROUP_FROM_ACTIVE_GROUP';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const SET_BASIC_USER_INFO = 'SET_BASIC_USER_INFO';

export const THROW_ERROR = 'THROW_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';



